### ISSUE TITLE
Nothing happens.

### ISSUE THREAD

**Issue by staminna** [egorFiNE/ropstenfaucet#1]
Dear egorFINE

I copy my public address from Metamask and past into the input field in https://faucet.egorfine.com/ 
then I wait but nothing happens.

```
faucet.egorfine.com

MetaMask is not connected to this site. To connect to a web3 site, find and click the connect button.
```

I don't know if Metamask should be connected to faucet.egorfine.com but I can't seem to find out how to connect and get the Ether. I am learning about blockchain and I don't know all the concepts yet :)

**Comment by egorFiNE** [comment]
Hi! No need to connect the faucet to metamask. You just paste your address to metamask and sometime in the future 0.3 ETH will land on your address. 

Right now faucet is overloaded, might not be quick :-(
