### ISSUE TITLE
Goerli Testnet

### ISSUE THREAD

**Issue by vm06007** [egorFiNE/ropstenfaucet#3]
Would you consider running this on Goerli?

**Comment by egorFiNE** [comment]
I'd love to!

Where do I source Goerli testnet eth?

**Comment by vm06007** [comment]
maybe we could setup some test-validator node? I'm currently checking with https://goerli.launchpad.ethstaker.cc/ and rocketpool..

**Comment by egorFiNE** [comment]
Well, that would yield personal amounts of gETH while we need so much more for this to be a public service.

**Comment by vm06007** [comment]
how did You acquire enough for same service on Ropsten before?

**Comment by egorFiNE** [comment]
One of the Ethereum OG gave me 100 mil rETH for the service.

**Comment by vm06007** [comment]
this one looks interesting: https://goerli-faucet.pk910.de/ :)

**Comment by egorFiNE** [comment]
@vm06007 yeah, that's what I have used I believe

since this ticket is non-actionable, I am closing it now.
